// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreIntecWeb.Models
{
    public partial class License
    {
        public License()
        {
            User = new HashSet<User>();
        }

        public DateTime CreatedAt { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool? Enabled { get; set; }

        public virtual ICollection<User> User { get; set; }
    }
}