// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace CoreIntecWeb.Models
{
    public partial class People
    {
        public People()
        {
            Company = new HashSet<Company>();
            User = new HashSet<User>();
        }

        public int Id { get; set; }
        [DisplayName("First Name")]
        public string FirstName { get; set; }
        [DisplayName("Middle Name")]
        public string MiddleName { get; set; }
        [DisplayName("Last Name")]
        public string LastName { get; set; }
        [DisplayName("Client Type")]
        public int ClientTypeId { get; set; }
        [DisplayName("Contact Type")]
        public int ContactTypeId { get; set; }

        [DisplayName("Is Staff?")]
        public bool SupportStaff { get; set; }
        [DisplayName("Phone Number")]
        public string PhoneNumber { get; set; }
        [DisplayName("Email Address")]
        public string EmailAddress { get; set; }
        [DisplayName("Company")]
        public int CompanyId { get; set; }
        public int DepartmentId { get; set; }
        [DisplayName("Created At")]
        public DateTime CreatedAt { get; set; }
        [DisplayName("Is Enabled?")]
        public bool Enabled { get; set; }
        [DisplayName("Client Type")]
        public virtual ClientType ClientType { get; set; }
        [DisplayName("Company")]
        public virtual Company CompanyNavigation { get; set; }
        [DisplayName("Contact Type")]
        public virtual ContactType ContactType { get; set; }
        [DisplayName("Department")]
        public virtual Department Department { get; set; }
        public virtual ICollection<Company> Company { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}