// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreIntecWeb.Models
{
    public partial class User
    {
        public User()
        {
            UserPermissions = new HashSet<UserPermissions>();
            UserRestrictions = new HashSet<UserRestrictions>();
        }

        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int LicenseTypeId { get; set; }
        public bool? Enabled { get; set; }
        public DateTime CreatedAt { get; set; }
        public int? PersonId { get; set; }

        public virtual License LicenseType { get; set; }
        public virtual People Person { get; set; }
        public virtual ICollection<UserPermissions> UserPermissions { get; set; }
        public virtual ICollection<UserRestrictions> UserRestrictions { get; set; }
    }
}