// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreIntecWeb.Models
{
    public partial class UserRestrictions
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int RestrictionId { get; set; }

        public virtual Restriction Restriction { get; set; }
        public virtual User User { get; set; }
    }
}